### ISSUE TITLE
Battlemaps downloads are incomplete

### ISSUE THREAD

**Issue by gbeine** [Forgotten-Adventures/FA_Battlemaps#10]
When I load a map on a Linux machine (Foundry 11, but the same issue also happens when I use Foundry 10), I get a protocol of a successful download (see screenshot), but only a part of the files appear within the `fa_battlemaps` folder.
This issue does not happen with my local Foundy on macOS.

Logfile:
```
FoundryVTT | 2023-07-02 13:59:52 | [info] Water_Droplets_A4_01.webm saved to fa_battlemaps/Animations
FoundryVTT | 2023-07-02 13:59:53 | [info] Water_Droplets_A3_01.webm saved to fa_battlemaps/Animations
FoundryVTT | 2023-07-02 13:59:53 | [info] Water_Droplets_A2_01.webm saved to fa_battlemaps/Animations
FoundryVTT | 2023-07-02 13:59:53 | [info] Water_Droplets_A1_01.webm saved to fa_battlemaps/Animations
FoundryVTT | 2023-07-02 13:59:53 | [info] Flies_A1_01.webm saved to fa_battlemaps/Animations
FoundryVTT | 2023-07-02 13:59:53 | [info] DustParticles_A1_01.webm saved to fa_battlemaps/Animations
FoundryVTT | 2023-07-02 13:59:56 | [info] Blood.webp saved to fa_battlemaps/Maps/2023/February/fa_swamp-d/Text
FoundryVTT | 2023-07-02 13:59:56 | [info] Dead.webp saved to fa_battlemaps/Maps/2023/February/fa_swamp-d/Text
FoundryVTT | 2023-07-02 13:59:56 | [info] Swamp.webp saved to fa_battlemaps/Maps/2023/February/fa_swamp-d/Text
FoundryVTT | 2023-07-02 13:59:56 | [info] FoundryVTT | Created Scene with id [anufFn5FNH9Z59lk]
FoundryVTT | 2023-07-02 13:59:56 | [info] FoundryVTT | Extracted base64 asset: "/var/lib/foundrydata/Data/worlds/gildenwelt/assets/scenes/anufFn5FNH9Z59lk-thumb.webp"

```

Screenshot of download
![Screenshot 2023-07-02 at 13 59 56](https://github.com/Forgotten-Adventures/FA_Battlemaps/assets/2093685/b300a547-f7ba-4ea0-a9dc-0a2247c41918)

Files that are successfully downloaded:
```
root@host16:/mnt/foundry-storage/foundrydata/Data# find fa_battlemaps -type f
fa_battlemaps/Maps/2023/February/fa_swamp-d/Text/Dead.webp
fa_battlemaps/Maps/2023/February/fa_swamp-d/Text/Blood.webp
fa_battlemaps/Maps/2023/February/fa_swamp-d/Text/Swamp.webp
fa_battlemaps/Animations/Flies_A1_01.webm
fa_battlemaps/Animations/Water_Droplets_A1_01.webm
fa_battlemaps/Animations/Water_Droplets_A2_01.webm
fa_battlemaps/Animations/Water_Droplets_A4_01.webm
fa_battlemaps/Animations/Water_Droplets_A3_01.webm
fa_battlemaps/Animations/DustParticles_A1_01.webm
```

The error is reproducible, even with a new installation of Foundry, the problem persists.
On macOS everything is fine.

Node is 18.16.1.

**Comment by sneat** [comment]
Hi @gbeine - as per #11 I wasn't able to replicate this exactly, but I did find an issue that is highly likely to be related. This fix will go into the next release, otherwise if you want to try it earlier, you can grab the file from https://github.com/Forgotten-Adventures/FA_Battlemaps/blob/await-uploads/scripts/fa-battlemaps.js and replace your copy at `modules/fa-battlemaps/scripts/fa-battlemaps.js`

**Comment by gbeine** [comment]
Hi @sneat - thank you very much for investigating in this issue!
I'll try and test if it solves the problem.

**Comment by sneat** [comment]
Did this solve your issue @gbeine ? v1.0.35 of the module includes the fix if you didn't want to change it manually.

**Comment by sneat** [comment]
Closing as I haven't heard anything further.

**Comment by donald-stolz** [comment]
I'm running Foundry 11.311 on Linux hosted with AWS, was having a similar issue where some files just didn't download. Found some 413 errors in the JS console and learned I had to update my NGINX proxy config. Just added `client_max_body_size 20M;` to the server settings. Hope this helps!

**Comment by gbeine** [comment]
@donald-stolz that seems to work, thank you.

I'd not expect that a server side download requires a parameter related to uploading files, but that's one of the JS/TS-related secrets I think ;-)
