### ISSUE TITLE
Cragmaw Hideout Walls, Tiles, Lights, Sound are offset

### ISSUE THREAD

**Issue by pesky-wobbit** [Forgotten-Adventures/FA_Battlemaps#2]
They all seem offset by the same amount. I was able to do a manual fix.

Walls can be moved en masse.
Tiles can be unlocked en masse, then moved together.
Lights and Sounds must be repositioned individually with the same offset. Not too hard. 

Flood animation is very cool!

**Comment by Stryxin** [comment]
I'm not able to reproduce this, might be some of your other modules interfering?

**Comment by pesky-wobbit** [comment]
You are correct. I believe the offending module is Core Settings Expanded.
Its scene defaults feature may be overstepping.

Great map. Thanks!
