### ISSUE TITLE
[Feature Request] Download path setting for assets

### ISSUE THREAD

**Issue by Krigsmaskine** [Forgotten-Adventures/FA_Battlemaps#8]
I'd like the module to be configurable to select where the module is downloading/importing the assets needed for the maps. Super ideally, I'd love if I could set individual sources of the folders inside (they already line up with my setup in `Data` anyway!), but would definitely "settle" for just being able to stuff the `fa_battlemaps` into a subfolder inside `Data`.

**Comment by sneat** [comment]
This is live now @Krigsmaskine in v1.1.0
